export const EMAIL_CHANGED="email_changed";
export const PASSWORD_CHANGED="password_changed";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const CREATE_SUCCESS="CREATE_SUCCESS";
export const ISLOADING="ISLOADING";

export const EMPLOYEE_UPDATE="EMPLOYEE_UPDATE";
export const EMPLOYEE_CREATE="EMPLOYEE_CREATE";
export const EMPLOYEE_FETCH_SUCCESS="EMPLOYEE_FETCH_SUCCESS";